<a href="https://colab.research.google.com/github/EunikeChristabelle/Python---Scientific-Computing/blob/main/02_03_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = [[8 , 3, -3], [-2, -8, 5], [3, 5, 10]]
# Find diagonal coefficients
diag = np.diag(np.abs(a))
#Find row sum without diagonal
off_diag = np.sum(np.abs(a), axis=1) - diag
print(diag)
print (off_diag)
if np.all(diag > off_diag):
  print('matrix is diagonally dominant')
else:
  print('NOT diagonaly dominant')


[ 8  8 10]
[6 7 8]
matrix is diagonally dominant


In [ ]:
import numpy as np
x1 = 0
x2 = 0
x3 = 0
epsilon = 0.01
converged = False

x_old = np.array([x1, x2, x3])

print('Iteration results')
print('k,   x1,      x2,      x3')
for k in range(1, 50):
  x1 = (14-3*x2+3*x3)/8
  x2 = (5+2*x1-5*x3)/(-8)
  x3 = (-8-3*x1-5*x2)/(10)
  x = np.array([x1, x2, x3])
  dx = np.sqrt(np.dot(x-x_old, x-x_old))

  print("%d, %.4f, %.4f, %.4f"%(k,x1,x2,x3))
  if dx < epsilon:
    converged = True
    print('converged!')
    break

  x_old = x

if not converged:
  print('Not converged, increase the # of iteration')

Iteration results
k,   x1,      x2,      x3
1, 1.7500, -1.0625, -0.7937
2, 1.8508, -1.5838, -0.5633
3, 2.1327, -1.5103, -0.6847
4, 2.0596, -1.5678, -0.6340
5, 2.1002, -1.5463, -0.6569
6, 2.0835, -1.5565, -0.6468
7, 2.0911, -1.5520, -0.6513
converged!


In [ ]:
#Not diagonally dominant
import numpy as np

A = np.array([[4,3,-5], [-2,-4,5],[8,8,0]])
y = np.array([2,5,-3])
x = np.linalg.solve(A,y)
print(x)

#Matrix inversion approach
A_inv = np.linalg.inv(A)
x = np.dot(A_inv, y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]
[ 2.20833333 -2.58333333 -0.18333333]


In [ ]:
import numpy as np
from scipy import optimize
import matplotlib.pyplot as plt

plt.style.use('seaborn-poster')

# generate x and y
x = np.linspace(0,1,101)
y = 1 + x + x * np.random.random(len(x))

# assemble matrix A
A = np.vstack([x, np.ones(len(x))]).T

# turn y into a column vector
y = y [:, np.newaxis]

# direct least square regression

alpha = np.dot((np.dot(np.linalg.inv(np.dot(A.T,A)), A.T)),y)
print(alpha)

[[1.52073665]
 [0.97791065]]


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

x = [0,1,2,3]
y = [0,1,4,9]

plt.plot(x,y)
plt.show()